### ISSUE TITLE
User profiles

### ISSUE THREAD

**Issue by vladimirbazhanov** [fs/rails-base#232]
Hi all.

I have an idea and want to ask, does this project need it :) We now have User model that contain one 'Full name field' Almost every projects requires user to have many fields, like first_name, last_name, phone number(s), some settings and personal data. I think it can be helpful to implement Profile model in rails-base for keeping there info not related to authentication. So, we can use User to store signin credentials (social networks connection data...) and Profile to store other user info. User model wiil not grow up and will be simple. Profile can also have a presenter to use in views.

If this sounds good I can prepare pull-request. Thanks!

**Comment by timurvafin** [comment]
@vladimirbazhanov, I'm not sure we would like to have separate model for profile instead of adding required fields directly to User model.

Any way this thing could be done in the `examples` brunch.
