### ISSUE TITLE
Try Pronto as a replacement for custom bin/quality

### ISSUE THREAD

**Issue by timurvafin** [fs/rails-base#240]
https://github.com/mmozuras/pronto

**Comment by ruslankhaertdinov** [comment]
@timurvafin I'll try to prepare PR for this one.

**Comment by ruslankhaertdinov** [comment]
There is an issue occurs when Semaphore installs gems: 
![failed build 3 of rails-base try-pronto-as-replacement-for-custom-script-240 - semaphore 2015-03-28 20-16-38](https://cloud.githubusercontent.com/assets/1073728/6882017/2d7a850c-d588-11e4-9e8f-258613cdc53d.png)

**Comment by ruslankhaertdinov** [comment]
@timurvafin can we close this issue?
