### ISSUE TITLE
Issue with truncation DB cleaner, while running feature capybara specs with JS

### ISSUE THREAD

**Issue by maximlarionov** [fs/rails-base#246]
Bumped into this issue while was testing form actions, based on AJAX with capybara feature specs.
Spec got frozen, and bin/ci couldn't pass.
Got this fixed in my PDP project - https://github.com/maximlarionov/pdp-blog/commit/032058b6acd408ddaf768c5a72bbd89f152d3bee#diff-4d41f2688fb9abaa2897572d409789f3L1

Also, found an original issue https://github.com/DatabaseCleaner/database_cleaner/issues/273

I guess, it needs some investigating, why it's happening, and how we should fix it.

**Comment by maximlarionov** [comment]
From what I've found:

Using an around hook ends up causing rspec to hang. Switching to a before and after hook works fine.
Seems like transaction can't be closed with around hook. 

Shall we switch to before(:each) - after(:each) hooks?

**Comment by timurvafin** [comment]
@maximlarionov you could try
