### ISSUE TITLE
Cookies Serializer JSON calls an error

### ISSUE THREAD

**Issue by maximlarionov** [fs/rails-base#293]
On opening app in Chrome, action_dispatch.cookies_serializer = :json causes 
```ActionView::Template::Error (795: unexpected token at I"session_id:ETI"%b7c0e19e7e39750921060ef3d9ba93e2;'): ```

![1 bin_server sh 2015-07-10 18-08-26](https://cloud.githubusercontent.com/assets/4546045/8621528/bb17122a-272e-11e5-8214-6149e574e475.png)

Seems like an source of issue.

https://github.com/rails/rails/issues/15111

**Comment by maximlarionov** [comment]
https://github.com/fs/rails-base/pull/294

**Comment by maximlarionov** [comment]
cc @timurvafin @VladimirMikhailov

**Comment by timurvafin** [comment]
@maximlarionov `hybrid` storage required only for existing application in case some users have cookies serialized with old format.

We assume new apps will use new `json` serialization format for all users from the begging.

I understand that it's cause issues when you develop different rails apps with different serialization on the same `localhost` domain. But should we stick for `hybrid` format only b/c of that?

**Comment by maximlarionov** [comment]
@timurvafin appears that you're totally right, hybrid cookie serialization was needed to migrate cookies from marshall to JSON. Totally not needed here.
