### ISSUE TITLE
rack-mini-profiler

### ISSUE THREAD

**Issue by timurvafin** [fs/rails-base#310]
http://www.nateberkopec.com/2015/08/05/rack-mini-profiler-the-secret-weapon.html

Could be based on https://github.com/fs/ofadaa/pull/406, with some improvements:
* extract mini profiler methods to controller concern

**Comment by ArthurZaharov** [comment]
@timurvafin Can I take this one?

**Comment by dmitrytrager** [comment]
can we close the issue?
