### ISSUE TITLE
newrelic

### ISSUE THREAD

**Issue by timurvafin** [fs/rails-base#311]
https://github.com/fs/ofadaa/pull/407

**Comment by dmitrytrager** [comment]
looks like [already](https://github.com/fs/rails-base/blob/master/Gemfile#L43) [implemented](https://github.com/fs/rails-base/blob/master/config/newrelic.yml)
let's close this one!

**Comment by timurvafin** [comment]
@dmitrytrager we could port it to rails-base-api
