### ISSUE TITLE
Authentication via Social Networks

### ISSUE THREAD

**Issue by timurvafin** [fs/rails-base#325]
* Signin/signup via Facebook/Google
* Connect/Disconnect social network from profile

**Comment by ruslankhaertdinov** [comment]
Please assign it to me, if issue steel actual.

**Comment by ruslankhaertdinov** [comment]
Could you please provide more description about this one?

**Comment by timurvafin** [comment]
The idea is to have some example how to organize authentication via Social networks.
There are should be ability to connect/disconnect network with current account from the profile page.

**Comment by ruslankhaertdinov** [comment]
Thanks!)
