### ISSUE TITLE
Cors setup for serving font assets from CDN

### ISSUE THREAD

**Issue by timurvafin** [fs/rails-base#339]
``` ruby
Rails.application.config.middleware.insert_before 0, "Rack::Cors", debug: true, logger: (-> { Rails.logger }) do
  allow do
    origins "*"
    resource "/assets/*", headers: :any, methods: :get
  end
end
```

Need to add configuration for `CORS_ORIGINS` via `ENV` variables.

Also we need to whitelist `Origin` header in Cloudfront https://stackoverflow.com/questions/32592571/cloudfront-cors-issue-serving-fonts-on-rails-application?answertab=active#tab-top

![](https://monosnap.com/file/6bKcPxa35QbsQg4m4mRFO6Qs3wZhxQ.png)

**Comment by ruslankhaertdinov** [comment]
@timurvafin seems like I don't have rights to view example link.
