### ISSUE TITLE
Escape JSON using Slim

### ISSUE THREAD

**Issue by VladimirMikhailov** [fs/rails-base#363]
https://github.com/fs/rails-base/blob/master/app/views/layouts/application.html.slim#L31

```slim
 javascript:
      App.currentUserData = #{raw current_user.to_json};
```

As far as I know we have to use slim's escape (`#{{}}`) method for better interaction with `JSON.parse`
https://github.com/slim-template/slim#output-without-html-escaping-

So, it should look like:

```slim
 javascript:
      App.currentUserData = #{{current_user.to_json}};
```

Please, add a few jasmine tests

**Comment by ruslankhaertdinov** [comment]
@VladimirMikhailov please give me a chance to prepare PR

**Comment by VladimirMikhailov** [comment]
@ruslankhaertdinov sure, np, but please make sure that we can reproduce the issue by jasmine tests and then fix it. Thanks

**Comment by ruslankhaertdinov** [comment]
@VladimirMikhailov It seems that Jasmine provides ability to test pure js, but how can I check an interaction in slim template? Not obvious for me.

**Comment by VladimirMikhailov** [comment]
@ruslankhaertdinov yes, you're right, likely it's no option to use jasmine tests here, but which approach would be the best then? Do you have any idea?

**Comment by ruslankhaertdinov** [comment]
@VladimirMikhailov later I try to solve it with capybara
