### ISSUE TITLE
Can't push new project when rails-base was cloned using --depth 1 key

### ISSUE THREAD

**Issue by vladimirbazhanov** [fs/rails-base#368]
When I cloned rails-base with --depth 1 key I can't push newrly created project to own repo becase git asks to do 'unshallow'

```
To git@github.com:vladimirbazhanov/rails-base.git
 ! [remote rejected] master -> master (shallow update not allowed)
```

Looks like shallow copy can't be pushed to new remote repository?

**Comment by timurvafin** [comment]
@vladimirbazhanov there are other issue related to `--depth 1`.

In case you cloned repository with `--depth 1` you will cut-off old commits from origin `fs/rails-base` repository, so you can't any more to pull new changes from upstream.

What do you think if we will remove these instruction completelly? 
I know @dmitrytrager added this thing initially, any thought?

**Comment by vladimirbazhanov** [comment]
I think it's better to remove it and avoid that two problems.

**Comment by timurvafin** [comment]
@vladimirbazhanov could you please open pull request for that?

**Comment by vladimirbazhanov** [comment]
@timurvafin will do

**Comment by dmitrytrager** [comment]
> In case you cloned repository with --depth 1 you will cut-off old commits from origin fs/rails-base repository, so you can't any more to pull new changes from upstream.

@timurvafin @vladimirbazhanov The goal of using `--depth 1` is to cut-off old commits and hide the fact of using existing repo for new project. If this does not matter, you should avoid using this parameter.

**Comment by dmitrytrager** [comment]
Of course, we also can do the things [manually](http://stackoverflow.com/questions/29748197/how-to-clone-seed-kick-start-project-without-the-whole-history).
