### ISSUE TITLE
Introduce Repository patten

### ISSUE THREAD

**Issue by timurvafin** [fs/rails-base#380]
https://www.amberbit.com/blog/2015/11/30/using-repository-pattern-to-migrate-rails-app-from-mongodb-to-postgresql/

**Comment by dmitrytrager** [comment]
Do we use MongoDB for this project?

**Comment by timurvafin** [comment]
Nope, we use PG by default.

**Comment by timurvafin** [comment]
> The key is to make sure that you won’t lose any query, which could break some of your functionalities. First step is based on the recipe proposed by Andrzej Krzywda in Fearless Refactoring. He recommends creating repositories for each model you are using or at least for the biggest and most complicated ones. By moving all your queries there, you can easily modify them later and change their syntax in the Active Record way. Same strategy apply to your tests.

**Comment by dmitrytrager** [comment]
Ok, I see.

**Comment by timurvafin** [comment]
TBD for sure.

**Comment by dmitrytrager** [comment]
Would like to handle it then.

**Comment by dmitrytrager** [comment]
@timurvafin Can I change label from enhancement to example?
