### ISSUE TITLE
Rename scenario titles in rspec features

### ISSUE THREAD

**Issue by artembiserov** [fs/rails-base#412]
if sign in spec fails, we receive next message
`1) Sign In Visitor signs in with valid credentials`
`Failure/Error: expect(page).to have_content("Sign out")`

maybe we should write something like this:
`feature "Visitor signs in" do`
`  scenario "with valid credentials"`

**Comment by timurvafin** [comment]
@artembiserov I don't thing your suggestion is valid. Scenario name should contain valid scenario description like "User creates a new widget", "User signs in".

To improve redability we could just put a `.` in `feature "Visitor signs in."` what will represent fail message like `Sign In. Visitor signs in with valid credentials`.

Feel free to propose this improvement in PR and reopen this issues if needed.
