### ISSUE TITLE
'master' branch should be protected from force-push at least

### ISSUE THREAD

**Issue by vladimirbazhanov** [fs/rails-base#423]
Hi!

Just want to make sure, is 'master' branch of rails-base protected from force-push in Settings -> Branches? I cant' check this myself...

Reason why I'm asking - we are using rails-base with students at ITIS lessons and it's possible that someone have cloned this repo with default origin - can we protect master from pushing in some way? If some of them forget to remove default origin (they are newbies))) and push his changes - it can broke something. May be there is any other option to disable pushes without PRs?

If you think this is not a problem, just close this issue, nevermind)

Thanks!

**Comment by timurvafin** [comment]
It is

![](https://monosnap.com/file/1Xlbnta9QsX1NslVfa90UmTd0XhqmN.png)
