### ISSUE TITLE
Merge conflicts due to CHANGELOG.md

### ISSUE THREAD

**Issue by ArturMinnullin** [fs/rails-base#425]
@timurvafin Upon merging a single merge request, all other unmerged PRs immediately have merge conflicts because of `CHANGELOG.md`. What I propose is to add `.gitattributes` file with `CHANGELOG merge=union` line inside. Instead of leaving conflicts the union merge option will resolve conflicts favouring both side of the lines. Please, share your thoughts.

**Comment by timurvafin** [comment]
@ArturMinnullin could you please provide example of `.gitattributes`? Nice idea!

**Comment by ArturMinnullin** [comment]
@timurvafin It's ridiculously simple. Something like:
```
CHANGELOG merge=union
```

**Comment by timurvafin** [comment]
@ArturMinnullin could you create PR for that please?
